server:
  port: 7002
spring:
  application:
    name: getway-web
  cloud:     #跨域支持
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_good_route
          uri: lb://goods  #根据服务名过滤  localhost:7002/api/template/search--》localhost:7002/template/search--》goods/template/search
          predicates:
          #- Path=/api/goods/**
          - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1  #设置令牌桶的填充速度
              redis-rate-limiter.burstCapacity: 1  #允许每1s最大请求数量
        - id: changgou_user_route
          uri: lb://user
          predicates:
          - Path=/api/user/**,/api/address/**,/api/areas/**,/api/crties/**,/api/provinces/**
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1  #设置令牌桶的填充速度
              redis-rate-limiter.burstCapacity: 1  #允许每1s最大请求数量
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1  #设置令牌桶的填充速度
                redis-rate-limiter.burstCapacity: 1  #允许每1s最大请求数量
        - id: changgou_order_route
          uri: lb://pay
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1  #设置令牌桶的填充速度
                redis-rate-limiter.burstCapacity: 1  #允许每1s最大请求数量
#          uri: http://localhost:18081
#          predicates:
#            - Path=/template/**    # http://localhost:7002/template/search--->http://localhost:18081/template/Search

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    perfer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
tokenKey: Authorization
